"""Compute similarity metrics and plots for inspected RAG retrieval results."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

DEFAULT_RESULT_DIR = Path("llm_cvd/analysis/similarity_rag_result")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--inspection-csv",
        default=str(DEFAULT_RESULT_DIR / "retrieval" / "rag_retrieval_inspection_cve_signature_db_k6.csv"),
        help="CSV generated by inspect_rag_retrieval.py.",
    )
    parser.add_argument(
        "--rag-dataset-root",
        default="dataset/signature_db_Vul_data.csv",
        help="RAG corpus CSV used by the FAISS index.",
    )
    parser.add_argument(
        "--target-dataset-csv",
        default="dataset/cve_Real_Vul_data.csv",
        help="Target CVE/Real_Vul-style CSV used as queries.",
    )
    parser.add_argument("--index-dir", default="llm_cvd/indexes")
    parser.add_argument("--index-name", default="signature_db_Vul_data_codebert")
    parser.add_argument("--embedding-model-name", default="microsoft/codebert-base")
    parser.add_argument("--device", default=None)
    parser.add_argument("--retrieval-batch-size", type=int, default=16)
    parser.add_argument(
        "--output-csv",
        default=str(DEFAULT_RESULT_DIR / "metrics" / "rag_similarity_metrics_cve_signature_db_k6.csv"),
    )
    parser.add_argument(
        "--output-rank-bar",
        default=str(DEFAULT_RESULT_DIR / "plots" / "rag_similarity_rank_bar_cve_signature_db_k6.png"),
    )
    parser.add_argument(
        "--output-heatmap",
        default=str(DEFAULT_RESULT_DIR / "plots" / "rag_similarity_heatmap_cve_signature_db_k6.png"),
    )
    parser.add_argument(
        "--output-source-distribution-csv",
        default=str(DEFAULT_RESULT_DIR / "source_distribution" / "rag_retrieved_source_distribution_cve_signature_db_k6.csv"),
    )
    parser.add_argument(
        "--output-source-distribution",
        default=str(DEFAULT_RESULT_DIR / "source_distribution" / "rag_retrieved_source_distribution_cve_signature_db_k6.png"),
    )
    parser.add_argument(
        "--output-cve-reference-csv",
        default=str(DEFAULT_RESULT_DIR / "source_distribution" / "rag_cve_reference_rate_cve_signature_db_k6.csv"),
    )
    parser.add_argument(
        "--output-cve-reference",
        default=str(DEFAULT_RESULT_DIR / "source_distribution" / "rag_cve_reference_rate_cve_signature_db_k6.png"),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.retrieval_batch_size < 1:
        raise ValueError("--retrieval-batch-size must be at least 1")

    import faiss

    from llm_cvd.data.juliet_loader import (
        load_juliet_csv_train_records,
        load_real_vul_records,
        parse_real_vul_csv,
    )
    from llm_cvd.retrieval.rag_retriever import CodeBertFaissRetriever

    inspection_rows = list(read_csv(Path(args.inspection_csv)))
    if not inspection_rows:
        raise ValueError(f"No inspection rows found: {args.inspection_csv}")

    train_records = load_juliet_csv_train_records(Path(args.rag_dataset_root))
    query_records = load_real_vul_records(args.target_dataset_csv)
    raw_query_rows = {
        str(row.get("unique_id") or row.get("file_name") or idx): row
        for idx, row in enumerate(
            parse_real_vul_csv(
                Path(args.target_dataset_csv).read_text(encoding="utf-8", errors="replace")
            )
        )
    }
    raw_train_rows = {
        str(row.get("unique_id") or row.get("file_name") or idx): row
        for idx, row in enumerate(
            parse_real_vul_csv(
                Path(args.rag_dataset_root).read_text(encoding="utf-8", errors="replace")
            )
        )
    }

    index_path = Path(args.index_dir) / f"{args.index_name}.index"
    index = faiss.read_index(str(index_path))
    db_vectors = reconstruct_vectors(index)
    db_norm_vectors = normalize_rows(db_vectors)

    retriever = CodeBertFaissRetriever(
        train_records=train_records,
        index_name=args.index_name,
        index_dir=Path(args.index_dir),
        embedding_model_name=args.embedding_model_name,
        device=args.device,
    )
    query_vectors = retriever.get_embeddings(
        [str(row["code"]) for row in query_records],
        batch_size=args.retrieval_batch_size,
        desc="Embedding CVE query records",
    )
    query_by_sample_id = {
        str(row.get("sample_id", idx)): query_vectors[idx]
        for idx, row in enumerate(query_records)
    }

    rows_by_query = group_rows_by_query(inspection_rows)
    output_rows: list[dict[str, Any]] = []
    for query_sample_id, rows in rows_by_query.items():
        query_vector = query_by_sample_id.get(str(query_sample_id))
        if query_vector is None:
            raise ValueError(f"Missing query embedding for sample_id={query_sample_id}")
        all_l2_distances = squared_l2_distances(db_vectors, query_vector)
        query_norm = normalize_rows(query_vector.reshape(1, -1))[0]
        rank1_distance = min(float(row["faiss_l2_distance"]) for row in rows)
        raw_query = raw_query_rows.get(str(query_sample_id), {})
        query_cwe_hint = extract_cwe_hint(
            " ".join(
                [
                    str(raw_query.get("source_signature_path", "")),
                    str(raw_query.get("project", "")),
                    str(raw_query.get("processed_func", "")),
                ]
            )
        )

        for row in rows:
            retrieved_index = int(row["retrieved_index"])
            retrieved_vector = db_vectors[retrieved_index]
            train_record = train_records[retrieved_index]
            raw_train = raw_train_rows.get(sample_id_value(train_record), {})
            source_category = classify_source_category(train_record, raw_train)
            reference_family = classify_reference_family(source_category)
            cosine_similarity = float(np.dot(query_norm, db_norm_vectors[retrieved_index]))
            l2_distance = float(row["faiss_l2_distance"])
            retrieved_cwe_hint = extract_cwe_hint(
                " ".join(
                    [
                        str(row.get("retrieved_project", "")),
                        str(row.get("retrieved_source", "")),
                        str(train_records[retrieved_index].get("code", "")),
                    ]
                )
            )
            enriched = dict(row)
            enriched.update(
                {
                    "retrieved_source_category": source_category,
                    "retrieved_reference_family": reference_family,
                    "retrieved_is_cve_reference": str(reference_family == "CVE/Open Source Project"),
                    "retrieved_source_detail": source_detail(train_record, raw_train),
                    "retrieved_source_signature_path": raw_train.get("source_signature_path", ""),
                    "cosine_similarity": f"{cosine_similarity:.6f}",
                    "distance_gap_from_rank1": f"{l2_distance - rank1_distance:.6f}",
                    "distance_percentile_in_db": f"{distance_percentile(all_l2_distances, l2_distance):.6f}",
                    "query_cwe_hint": query_cwe_hint,
                    "retrieved_cwe_hint": retrieved_cwe_hint,
                    "cwe_matches_query_hint": cwe_match(query_cwe_hint, retrieved_cwe_hint),
                }
            )
            output_rows.append(enriched)

    output_csv = Path(args.output_csv)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    write_csv(output_csv, output_rows)
    write_rank_bar(Path(args.output_rank_bar), output_rows)
    write_heatmap(Path(args.output_heatmap), output_rows)
    write_source_distribution_csv(Path(args.output_source_distribution_csv), output_rows)
    write_source_distribution_plot(Path(args.output_source_distribution), output_rows)
    write_cve_reference_csv(Path(args.output_cve_reference_csv), output_rows)
    write_cve_reference_plot(Path(args.output_cve_reference), output_rows)

    print(f"Wrote similarity metrics CSV: {output_csv}")
    print(f"Wrote rank bar plot: {args.output_rank_bar}")
    print(f"Wrote heatmap: {args.output_heatmap}")
    print(f"Wrote source distribution CSV: {args.output_source_distribution_csv}")
    print(f"Wrote source distribution plot: {args.output_source_distribution}")
    print(f"Wrote CVE reference CSV: {args.output_cve_reference_csv}")
    print(f"Wrote CVE reference plot: {args.output_cve_reference}")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def reconstruct_vectors(index: Any) -> np.ndarray:
    try:
        return index.reconstruct_n(0, index.ntotal).astype(np.float32)
    except AttributeError:
        return np.vstack([index.reconstruct(idx) for idx in range(index.ntotal)]).astype(np.float32)


def normalize_rows(vectors: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    norms[norms == 0.0] = 1.0
    return vectors / norms


def squared_l2_distances(vectors: np.ndarray, query_vector: np.ndarray) -> np.ndarray:
    diff = vectors - query_vector.reshape(1, -1)
    return np.einsum("ij,ij->i", diff, diff)


def distance_percentile(all_distances: np.ndarray, distance: float) -> float:
    return float(np.mean(all_distances <= distance))


def group_rows_by_query(rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        grouped.setdefault(str(row["query_sample_id"]), []).append(row)
    for query_rows in grouped.values():
        query_rows.sort(key=lambda row: int(row["rank"]))
    return grouped


def extract_cwe_hint(text: str) -> str:
    values = sorted({f"CWE-{match}" for match in re.findall(r"CWE[-_]?(\d+)", text, re.I)})
    return ";".join(values)


def cwe_match(left: str, right: str) -> str:
    if not left or not right:
        return ""
    return "True" if set(left.split(";")) & set(right.split(";")) else "False"


def sample_id_value(record: dict[str, Any]) -> str:
    sample_id = str(record.get("sample_id", ""))
    if sample_id.startswith("juliet-csv::"):
        return sample_id.split("::", 1)[1]
    return sample_id


def classify_source_category(record: dict[str, Any], raw_record: dict[str, str]) -> str:
    project = str(record.get("project", "") or raw_record.get("project", ""))
    source_path = str(raw_record.get("source_signature_path", "") or record.get("source", ""))
    text = f"{project} {source_path}".lower()
    if "owasp" in text:
        return "OWASP Tutorial"
    if re.match(r"^CWE\d+_", project) or "signature-db-ori/cwe" in text:
        return "Juliet"
    if project:
        return "Open Source Project"
    return "Unknown"


def classify_reference_family(source_category: str) -> str:
    if source_category == "Open Source Project":
        return "CVE/Open Source Project"
    if source_category == "OWASP Tutorial":
        return "OWASP Tutorial"
    if source_category == "Juliet":
        return "Juliet"
    return "Unknown"


def source_detail(record: dict[str, Any], raw_record: dict[str, str]) -> str:
    project = str(record.get("project", "") or raw_record.get("project", ""))
    path = str(raw_record.get("source_signature_path", ""))
    if project:
        return project
    if path:
        return path
    return "Unknown"


def write_rank_bar(path: Path, rows: list[dict[str, Any]]) -> None:
    import matplotlib.pyplot as plt

    grouped = group_rows_by_query([{key: str(value) for key, value in row.items()} for row in rows])
    query_ids = list(grouped.keys())
    cols = 4
    rows_count = int(np.ceil(len(query_ids) / cols))
    fig, axes = plt.subplots(rows_count, cols, figsize=(16, max(8, rows_count * 2.6)), dpi=180)
    axes_flat = np.array(axes).reshape(-1)
    for ax, query_id in zip(axes_flat, query_ids):
        query_rows = grouped[query_id]
        ranks = [int(row["rank"]) for row in query_rows]
        distances = [float(row["faiss_l2_distance"]) for row in query_rows]
        cosines = [float(row["cosine_similarity"]) for row in query_rows]
        ax.bar(ranks, distances, color="#4c78a8", alpha=0.82, label="L2")
        ax2 = ax.twinx()
        ax2.plot(ranks, cosines, color="#f58518", marker="o", linewidth=1.3, label="Cosine")
        ax.set_title(f"Q{query_id}", fontsize=9)
        ax.set_xticks(ranks)
        ax.tick_params(axis="both", labelsize=7)
        ax2.tick_params(axis="y", labelsize=7)
        ax.grid(axis="y", linewidth=0.3, alpha=0.35)
    for ax in axes_flat[len(query_ids) :]:
        ax.axis("off")
    fig.suptitle("Top-6 RAG Similarity by Query", fontsize=13)
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def write_heatmap(path: Path, rows: list[dict[str, Any]]) -> None:
    import matplotlib.pyplot as plt

    grouped = group_rows_by_query([{key: str(value) for key, value in row.items()} for row in rows])
    query_ids = list(grouped.keys())
    max_rank = max(int(row["rank"]) for row in rows)
    matrix = np.full((len(query_ids), max_rank), np.nan, dtype=np.float32)
    for query_idx, query_id in enumerate(query_ids):
        for row in grouped[query_id]:
            matrix[query_idx, int(row["rank"]) - 1] = float(row["cosine_similarity"])

    fig, ax = plt.subplots(figsize=(9, max(5, len(query_ids) * 0.35)), dpi=180)
    image = ax.imshow(matrix, aspect="auto", cmap="viridis")
    ax.set_title("Top-6 Cosine Similarity Heatmap")
    ax.set_xlabel("Retrieved rank")
    ax.set_ylabel("CVE query sample")
    ax.set_xticks(np.arange(max_rank), labels=[str(rank) for rank in range(1, max_rank + 1)])
    ax.set_yticks(np.arange(len(query_ids)), labels=[f"Q{query_id}" for query_id in query_ids])
    ax.tick_params(axis="both", labelsize=8)
    for row_idx in range(matrix.shape[0]):
        for col_idx in range(matrix.shape[1]):
            value = matrix[row_idx, col_idx]
            if np.isfinite(value):
                ax.text(col_idx, row_idx, f"{value:.2f}", ha="center", va="center", fontsize=6, color="white")
    fig.colorbar(image, ax=ax, label="Cosine similarity")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def write_source_distribution_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    from collections import Counter

    total_counter = Counter(str(row["retrieved_source_category"]) for row in rows)
    unique_counter = Counter(
        str(next_row["retrieved_source_category"])
        for next_row in unique_rows_by_retrieved_sample(rows)
    )
    output_rows = []
    categories = sorted(set(total_counter) | set(unique_counter))
    for category in categories:
        total_count = total_counter[category]
        unique_count = unique_counter[category]
        output_rows.append(
            {
                "source_category": category,
                "retrieved_rank_instances": total_count,
                "retrieved_rank_instance_ratio": f"{total_count / len(rows):.6f}",
                "unique_retrieved_samples": unique_count,
                "unique_retrieved_sample_ratio": f"{unique_count / max(1, len(unique_rows_by_retrieved_sample(rows))):.6f}",
            }
        )
    write_csv(path, output_rows)


def unique_rows_by_retrieved_sample(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen = set()
    unique_rows = []
    for row in rows:
        sample_id = str(row.get("retrieved_sample_id", ""))
        if sample_id in seen:
            continue
        seen.add(sample_id)
        unique_rows.append(row)
    return unique_rows


def write_source_distribution_plot(path: Path, rows: list[dict[str, Any]]) -> None:
    from collections import Counter

    import matplotlib.pyplot as plt

    categories = ["Open Source Project", "OWASP Tutorial", "Juliet", "Unknown"]
    colors = {
        "Open Source Project": "#4c78a8",
        "OWASP Tutorial": "#f58518",
        "Juliet": "#54a24b",
        "Unknown": "#9ca3af",
    }
    total_counter = Counter(str(row["retrieved_source_category"]) for row in rows)
    unique_counter = Counter(
        str(row["retrieved_source_category"]) for row in unique_rows_by_retrieved_sample(rows)
    )
    query_ids = list(group_rows_by_query([{key: str(value) for key, value in row.items()} for row in rows]).keys())
    per_query = {
        query_id: Counter(
            str(row["retrieved_source_category"])
            for row in rows
            if str(row["query_sample_id"]) == query_id
        )
        for query_id in query_ids
    }

    fig, (ax_total, ax_query) = plt.subplots(
        2,
        1,
        figsize=(12, max(8, len(query_ids) * 0.32 + 4)),
        dpi=180,
        gridspec_kw={"height_ratios": [1, 1.8]},
    )
    x = np.arange(len(categories))
    width = 0.36
    total_values = [total_counter[category] for category in categories]
    unique_values = [unique_counter[category] for category in categories]
    ax_total.bar(
        x - width / 2,
        total_values,
        width,
        label="Rank instances",
        color=[colors[category] for category in categories],
        alpha=0.85,
    )
    ax_total.bar(
        x + width / 2,
        unique_values,
        width,
        label="Unique samples",
        color=[colors[category] for category in categories],
        alpha=0.45,
        hatch="//",
    )
    ax_total.set_title("Retrieved Top-6 Source Distribution")
    ax_total.set_ylabel("Count")
    ax_total.set_xticks(x, labels=categories, rotation=12, ha="right")
    ax_total.legend(frameon=False)
    ax_total.grid(axis="y", linewidth=0.3, alpha=0.35)

    bottoms = np.zeros(len(query_ids), dtype=np.float32)
    y = np.arange(len(query_ids))
    for category in categories:
        values = np.array([per_query[query_id][category] for query_id in query_ids], dtype=np.float32)
        ax_query.barh(
            y,
            values,
            left=bottoms,
            color=colors[category],
            label=category,
            alpha=0.88,
        )
        bottoms += values
    ax_query.set_title("Source Distribution per CVE Query")
    ax_query.set_xlabel("Retrieved samples among top-6")
    ax_query.set_ylabel("CVE query sample")
    ax_query.set_yticks(y, labels=[f"Q{query_id}" for query_id in query_ids])
    ax_query.set_xlim(0, 6)
    ax_query.invert_yaxis()
    ax_query.legend(frameon=False, ncol=2, loc="lower right")
    ax_query.grid(axis="x", linewidth=0.3, alpha=0.35)

    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def write_cve_reference_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    from collections import Counter

    total_counter = Counter(str(row["retrieved_reference_family"]) for row in rows)
    unique_rows = unique_rows_by_retrieved_sample(rows)
    unique_counter = Counter(str(row["retrieved_reference_family"]) for row in unique_rows)
    query_ids = sorted({str(row["query_sample_id"]) for row in rows}, key=lambda value: int(value))

    output_rows = [
        {
            "scope": "all_rank_instances",
            "query_sample_id": "",
            "cve_reference_count": total_counter["CVE/Open Source Project"],
            "total_retrieved": len(rows),
            "cve_reference_rate": f"{total_counter['CVE/Open Source Project'] / len(rows):.6f}",
        },
        {
            "scope": "unique_retrieved_samples",
            "query_sample_id": "",
            "cve_reference_count": unique_counter["CVE/Open Source Project"],
            "total_retrieved": len(unique_rows),
            "cve_reference_rate": f"{unique_counter['CVE/Open Source Project'] / max(1, len(unique_rows)):.6f}",
        },
    ]
    for query_id in query_ids:
        query_rows = [row for row in rows if str(row["query_sample_id"]) == query_id]
        cve_count = sum(
            1
            for row in query_rows
            if str(row["retrieved_reference_family"]) == "CVE/Open Source Project"
        )
        output_rows.append(
            {
                "scope": "per_query_top6",
                "query_sample_id": query_id,
                "cve_reference_count": cve_count,
                "total_retrieved": len(query_rows),
                "cve_reference_rate": f"{cve_count / max(1, len(query_rows)):.6f}",
            }
        )
    write_csv(path, output_rows)


def write_cve_reference_plot(path: Path, rows: list[dict[str, Any]]) -> None:
    import matplotlib.pyplot as plt

    grouped = group_rows_by_query([{key: str(value) for key, value in row.items()} for row in rows])
    query_ids = list(grouped.keys())
    rates = []
    for query_id in query_ids:
        query_rows = grouped[query_id]
        cve_count = sum(
            1
            for row in query_rows
            if str(row["retrieved_reference_family"]) == "CVE/Open Source Project"
        )
        rates.append(cve_count / max(1, len(query_rows)))

    overall_rate = sum(
        1
        for row in rows
        if str(row["retrieved_reference_family"]) == "CVE/Open Source Project"
    ) / len(rows)

    fig, (ax_overall, ax_query) = plt.subplots(
        2,
        1,
        figsize=(11, max(7, len(query_ids) * 0.32 + 3.5)),
        dpi=180,
        gridspec_kw={"height_ratios": [1, 1.8]},
    )
    ax_overall.bar(
        ["CVE/OSS reference", "Other reference"],
        [overall_rate, 1.0 - overall_rate],
        color=["#4c78a8", "#d1d5db"],
    )
    ax_overall.set_ylim(0, 1)
    ax_overall.set_ylabel("Rate")
    ax_overall.set_title(f"Overall CVE/OSS Reference Rate: {overall_rate:.1%}")
    for index, value in enumerate([overall_rate, 1.0 - overall_rate]):
        ax_overall.text(index, value + 0.02, f"{value:.1%}", ha="center", fontsize=9)
    ax_overall.grid(axis="y", linewidth=0.3, alpha=0.35)

    y = np.arange(len(query_ids))
    ax_query.barh(y, rates, color="#4c78a8", alpha=0.9)
    ax_query.set_xlim(0, 1)
    ax_query.set_xlabel("CVE/OSS references among top-6")
    ax_query.set_ylabel("CVE query sample")
    ax_query.set_title("CVE/OSS Reference Rate per Query")
    ax_query.set_yticks(y, labels=[f"Q{query_id}" for query_id in query_ids])
    ax_query.invert_yaxis()
    for row_index, value in enumerate(rates):
        ax_query.text(min(0.98, value + 0.02), row_index, f"{value:.0%}", va="center", fontsize=7)
    ax_query.grid(axis="x", linewidth=0.3, alpha=0.35)

    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


if __name__ == "__main__":
    main()
