"""Prepare a compact CSV for qualitative review of retrieved RAG examples.

The output intentionally excludes label-match columns so reviewers can focus on
whether retrieved traces share the same vulnerability cause and code context as
the queried CVE trace.
"""

from __future__ import annotations

import argparse
import csv
import html
import sys
from collections import defaultdict
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


REVIEW_FIELDS = [
    "query_sample_id",
    "query_project",
    "rank",
    "faiss_l2_distance",
    "query_snippet",
    "retrieved_snippet",
    "cause_match",
    "context_match",
    "helpful_as_fewshot",
    "note",
]

DEFAULT_INPUT = "results/rag_retrieval_inspection_cve_k6.csv"
DEFAULT_OUTPUT = "results/rag_retrieval_qualitative_review_cve_k6.csv"
DEFAULT_GROUPED_HTML = "results/rag_retrieval_qualitative_review_cve_k6_grouped_full.html"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-csv",
        default=DEFAULT_INPUT,
        help="Inspection CSV generated by inspect_rag_retrieval.py.",
    )
    parser.add_argument(
        "--output-csv",
        default=DEFAULT_OUTPUT,
        help="Compact qualitative review CSV to write.",
    )
    parser.add_argument(
        "--overwrite-notes",
        action="store_true",
        help="Clear existing manual review notes when reformatting a review CSV.",
    )
    parser.add_argument(
        "--output-html",
        default=None,
        help="Optional HTML table with wrapped snippet/note columns for easier reading.",
    )
    parser.add_argument(
        "--output-grouped-html",
        default=None,
        help="Optional grouped HTML review page with full query/retrieved code.",
    )
    parser.add_argument(
        "--target-dataset-csv",
        default="../dataset/cve_Real_Vul_data.csv",
        help="Target CVE CSV used to recover full query code for grouped HTML.",
    )
    parser.add_argument(
        "--rag-dataset-root",
        default="../dataset/juliet_Real_Vul_data.csv",
        help="RAG train CSV used to recover full retrieved code for grouped HTML.",
    )
    parser.add_argument(
        "--embedding-model-name",
        default="microsoft/codebert-base",
        help="Tokenizer name used by the RAG embedding model.",
    )
    parser.add_argument(
        "--max-rag-tokens",
        type=int,
        default=512,
        help="Maximum CodeBERT tokens used by the RAG embedding path.",
    )
    parser.add_argument(
        "--embedding-truncation-side",
        choices=("left", "right"),
        default="left",
        help="Tokenizer truncation side used by the RAG embedding path. 'left' keeps tail tokens.",
    )
    parser.add_argument(
        "--include-token-list",
        action="store_true",
        help="Include raw CodeBERT token lists in grouped HTML. This makes the file much heavier.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = Path(args.input_csv)
    output_path = Path(args.output_csv)

    if not input_path.exists():
        raise FileNotFoundError(f"Input CSV does not exist: {input_path}")

    rows = read_review_rows(input_path, overwrite_notes=args.overwrite_notes)
    if not rows:
        raise ValueError(f"Input CSV has no rows: {input_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=REVIEW_FIELDS)
        writer.writeheader()
        writer.writerows({field: row.get(field, "") for field in REVIEW_FIELDS} for row in rows)

    if args.output_html:
        write_html_review(Path(args.output_html), rows)
    if args.output_grouped_html:
        write_grouped_full_html(
            Path(args.output_grouped_html),
            rows,
            target_dataset_csv=Path(args.target_dataset_csv),
            rag_dataset_root=Path(args.rag_dataset_root),
            embedding_model_name=args.embedding_model_name,
            max_rag_tokens=args.max_rag_tokens,
            embedding_truncation_side=args.embedding_truncation_side,
            include_token_list=args.include_token_list,
        )

    query_count = len({row["query_sample_id"] for row in rows})
    print(f"Wrote {len(rows)} rows for {query_count} CVE queries to {output_path}")
    if args.output_html:
        print(f"Wrote wrapped HTML review table to {args.output_html}")
    if args.output_grouped_html:
        print(f"Wrote grouped full-code HTML review page to {args.output_grouped_html}")
    print("Manual columns: cause_match, context_match, helpful_as_fewshot, note")
    print("Suggested values: yes / partial / no")


def read_review_rows(input_path: Path, overwrite_notes: bool) -> list[dict[str, str]]:
    with input_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        validate_columns(reader.fieldnames or [])
        rows = []
        for row in reader:
            rows.append(
                {
                    "query_sample_id": row.get("query_sample_id", ""),
                    "query_project": row.get("query_project", ""),
                    "rank": row.get("rank", ""),
                    "faiss_l2_distance": row.get("faiss_l2_distance", ""),
                    "query_snippet": row.get("query_snippet", ""),
                    "retrieved_sample_id": row.get("retrieved_sample_id", ""),
                    "retrieved_snippet": row.get("retrieved_snippet", ""),
                    "cause_match": note_value(row, "cause_match", overwrite_notes),
                    "context_match": note_value(row, "context_match", overwrite_notes),
                    "helpful_as_fewshot": note_value(row, "helpful_as_fewshot", overwrite_notes),
                    "note": note_value(row, "note", overwrite_notes),
                }
            )
    return rows


def validate_columns(fieldnames: list[str]) -> None:
    required = {
        "query_sample_id",
        "query_project",
        "rank",
        "faiss_l2_distance",
        "query_snippet",
        "retrieved_snippet",
    }
    missing = sorted(required - set(fieldnames))
    if missing:
        raise ValueError(f"Input CSV is missing required columns: {', '.join(missing)}")


def note_value(row: dict[str, str], field: str, overwrite_notes: bool) -> str:
    if overwrite_notes:
        return ""
    return row.get(field, "")


def write_html_review(output_path: Path, rows: list[dict[str, str]]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        handle.write(
            """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>RAG Qualitative Review</title>
<style>
body {
  margin: 24px;
  color: #1f2933;
  font-family: Arial, sans-serif;
}
table {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
}
th, td {
  border: 1px solid #d0d7de;
  padding: 6px 8px;
  vertical-align: top;
  font-size: 13px;
}
th {
  position: sticky;
  top: 0;
  background: #f6f8fa;
  z-index: 1;
}
.narrow {
  width: 72px;
  text-align: center;
}
.distance {
  width: 110px;
}
.snippet {
  width: 34%;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}
.note {
  width: 18%;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
.toolbar {
  display: flex;
  gap: 12px;
  align-items: center;
  margin: 12px 0 18px;
}
button {
  border: 1px solid #57606a;
  border-radius: 6px;
  background: #ffffff;
  padding: 7px 11px;
  cursor: pointer;
}
select, textarea {
  width: 100%;
  box-sizing: border-box;
  border: 1px solid #d0d7de;
  border-radius: 4px;
  font: inherit;
}
textarea {
  min-height: 72px;
  resize: vertical;
}
</style>
</head>
<body>
<h1>RAG Qualitative Review</h1>
<div class="toolbar">
  <button type="button" onclick="exportCsv()">Export edited CSV</button>
  <span>Fill manual columns with yes / partial / no, then export.</span>
</div>
<table>
<thead>
<tr>
"""
        )
        for field in REVIEW_FIELDS:
            handle.write(f"<th class=\"{column_class(field)}\">{html.escape(field)}</th>\n")
        handle.write("</tr>\n</thead>\n<tbody>\n")
        for row in rows:
            handle.write("<tr>\n")
            for field in REVIEW_FIELDS:
                handle.write(
                    f"<td class=\"{column_class(field)}\" "
                    f"data-field=\"{html.escape(field)}\">"
                )
                write_cell(handle, field, row.get(field, ""))
                handle.write("</td>\n")
            handle.write("</tr>\n")
        handle.write(
            """</tbody>
</table>
<script>
const reviewFields = """
        )
        handle.write(str(REVIEW_FIELDS).replace("'", '"'))
        handle.write(
            """;

function csvEscape(value) {
  const text = String(value ?? "");
  if (/[",\n\r]/.test(text)) {
    return '"' + text.replaceAll('"', '""') + '"';
  }
  return text;
}

function cellValue(cell) {
  const field = cell.dataset.field;
  if (["cause_match", "context_match", "helpful_as_fewshot"].includes(field)) {
    return cell.querySelector("select").value;
  }
  if (field === "note") {
    return cell.querySelector("textarea").value;
  }
  return cell.textContent;
}

function exportCsv() {
  const lines = [reviewFields.map(csvEscape).join(",")];
  document.querySelectorAll("tbody tr").forEach((row) => {
    const values = Array.from(row.querySelectorAll("td")).map(cellValue);
    lines.push(values.map(csvEscape).join(","));
  });
  const blob = new Blob([lines.join("\\n") + "\\n"], {type: "text/csv;charset=utf-8"});
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "rag_retrieval_qualitative_review_cve_k6_filled.csv";
  link.click();
  URL.revokeObjectURL(url);
}
</script>
</body>
</html>
"""
        )


def write_grouped_full_html(
    output_path: Path,
    rows: list[dict[str, str]],
    target_dataset_csv: Path,
    rag_dataset_root: Path,
    embedding_model_name: str,
    max_rag_tokens: int,
    embedding_truncation_side: str,
    include_token_list: bool,
) -> None:
    full_codes = load_full_code_maps(target_dataset_csv, rag_dataset_root)
    tokenizer = load_embedding_tokenizer(embedding_model_name)
    tokenizer.truncation_side = embedding_truncation_side
    token_cache: dict[str, dict[str, str | bool | int]] = {}
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[row["query_sample_id"]].append(row)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        handle.write(
            """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>RAG Full-Code Qualitative Review</title>
<style>
body {
  margin: 24px;
  color: #1f2933;
  font-family: Arial, sans-serif;
}
.toolbar {
  display: flex;
  gap: 12px;
  align-items: center;
  margin: 12px 0 22px;
  position: sticky;
  top: 0;
  background: #ffffff;
  padding: 8px 0;
  z-index: 2;
}
button {
  border: 1px solid #57606a;
  border-radius: 6px;
  background: #ffffff;
  padding: 7px 11px;
  cursor: pointer;
}
section {
  border-top: 2px solid #8c959f;
  padding-top: 18px;
  margin-top: 28px;
}
.query-meta {
  color: #57606a;
  margin-bottom: 10px;
}
details {
  border: 1px solid #d0d7de;
  border-radius: 6px;
  margin: 10px 0;
  background: #ffffff;
}
summary {
  cursor: pointer;
  padding: 8px 10px;
  background: #f6f8fa;
}
pre {
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  margin: 0;
  padding: 12px;
  background: #f6f8fa;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 13px;
  line-height: 1.35;
}
.retrieved pre {
  background: #ffffff;
  border-top: 1px solid #d0d7de;
}
.token-box {
  border-top: 1px solid #d0d7de;
  padding: 10px;
  background: #fff8c5;
}
.token-box details {
  margin: 8px 0 0;
  background: #ffffff;
}
.token-meta {
  color: #57606a;
  font-size: 13px;
  margin-bottom: 8px;
}
.token-text {
  background: #fffdf0;
  border: 1px solid #d0d7de;
}
.token-list {
  max-height: 240px;
  overflow: auto;
}
.manual {
  display: grid;
  grid-template-columns: repeat(3, minmax(120px, 1fr)) minmax(240px, 2fr);
  gap: 10px;
  padding: 10px;
  border-top: 1px solid #d0d7de;
}
label {
  display: flex;
  flex-direction: column;
  gap: 4px;
  font-size: 12px;
  color: #57606a;
}
select, textarea {
  width: 100%;
  box-sizing: border-box;
  border: 1px solid #d0d7de;
  border-radius: 4px;
  font: inherit;
  color: #1f2933;
}
textarea {
  min-height: 58px;
  resize: vertical;
}
</style>
</head>
<body>
<h1>RAG Full-Code Qualitative Review</h1>
<div class="toolbar">
  <button type="button" onclick="exportCsv()">Export edited CSV</button>
  <span>Query code is shown once per CVE; retrieved full code is grouped below it.</span>
</div>
"""
        )

        for query_id in sorted(grouped, key=lambda value: int(value) if value.isdigit() else value):
            group = sorted(grouped[query_id], key=lambda row: int(row["rank"]))
            first = group[0]
            query_code = full_codes["queries"].get(query_id, first["query_snippet"])
            query_token_info = token_info(
                tokenizer,
                query_code,
                max_rag_tokens=max_rag_tokens,
                truncation_side=embedding_truncation_side,
                cache=token_cache,
                include_token_list=include_token_list,
            )
            handle.write(
                f"<section data-query-id=\"{html.escape(query_id)}\" "
                f"data-query-project=\"{html.escape(first['query_project'])}\">\n"
                f"<h2>Query {html.escape(query_id)}: {html.escape(first['query_project'])}</h2>\n"
                "<div class=\"query-meta\">Full query code</div>\n"
                f"<pre class=\"query-code\">{html.escape(query_code)}</pre>\n"
            )
            write_token_box(
                handle,
                "CodeBERT input used for query embedding",
                query_token_info,
                include_token_list=include_token_list,
            )
            for row in group:
                retrieved_key = row.get("retrieved_sample_id", "")
                retrieved_code = full_codes["retrieved"].get(retrieved_key, row["retrieved_snippet"])
                retrieved_token_info = token_info(
                    tokenizer,
                    retrieved_code,
                    max_rag_tokens=max_rag_tokens,
                    truncation_side=embedding_truncation_side,
                    cache=token_cache,
                    include_token_list=include_token_list,
                )
                handle.write(
                    "<details class=\"retrieved\" "
                    f"data-rank=\"{html.escape(row['rank'])}\" "
                    f"data-distance=\"{html.escape(row['faiss_l2_distance'])}\">\n"
                    f"<summary>Rank {html.escape(row['rank'])} "
                    f"| FAISS L2 {html.escape(row['faiss_l2_distance'])} "
                    f"| {html.escape(retrieved_key)}</summary>\n"
                    f"<pre class=\"retrieved-code\">{html.escape(retrieved_code)}</pre>\n"
                )
                write_token_box(
                    handle,
                    "CodeBERT input used for retrieved embedding",
                    retrieved_token_info,
                    include_token_list=include_token_list,
                )
                handle.write("<div class=\"manual\">\n")
                for field in ["cause_match", "context_match", "helpful_as_fewshot"]:
                    handle.write(f"<label>{html.escape(field)}")
                    write_select(handle, field, row.get(field, ""))
                    handle.write("</label>\n")
                handle.write(
                    "<label>note"
                    f"<textarea data-field=\"note\">{html.escape(row.get('note', ''))}</textarea>"
                    "</label>\n"
                    "</div>\n"
                    "</details>\n"
                )
            handle.write("</section>\n")

        handle.write(
            """<script>
const outputFields = [
  "query_sample_id",
  "query_project",
  "rank",
  "faiss_l2_distance",
  "query_code",
  "retrieved_code",
  "cause_match",
  "context_match",
  "helpful_as_fewshot",
  "note"
];

function csvEscape(value) {
  const text = String(value ?? "");
  if (/[",\n\r]/.test(text)) {
    return '"' + text.replaceAll('"', '""') + '"';
  }
  return text;
}

function exportCsv() {
  const lines = [outputFields.map(csvEscape).join(",")];
  document.querySelectorAll("section").forEach((section) => {
    const queryId = section.dataset.queryId;
    const queryProject = section.dataset.queryProject;
    const queryCode = section.querySelector(".query-code").textContent;
    section.querySelectorAll("details.retrieved").forEach((item) => {
      const values = [
        queryId,
        queryProject,
        item.dataset.rank,
        item.dataset.distance,
        queryCode,
        item.querySelector(".retrieved-code").textContent,
        item.querySelector('[data-field="cause_match"]').value,
        item.querySelector('[data-field="context_match"]').value,
        item.querySelector('[data-field="helpful_as_fewshot"]').value,
        item.querySelector('[data-field="note"]').value
      ];
      lines.push(values.map(csvEscape).join(","));
    });
  });
  const blob = new Blob([lines.join("\\n") + "\\n"], {type: "text/csv;charset=utf-8"});
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "rag_retrieval_qualitative_review_cve_k6_full_filled.csv";
  link.click();
  URL.revokeObjectURL(url);
}
</script>
</body>
</html>
"""
        )


def load_full_code_maps(target_dataset_csv: Path, rag_dataset_root: Path) -> dict[str, dict[str, str]]:
    from llm_cvd.data.juliet_loader import load_juliet_csv_train_records, load_real_vul_records

    query_records = load_real_vul_records(target_dataset_csv)
    retrieved_records = load_juliet_csv_train_records(rag_dataset_root)
    return {
        "queries": {str(row["sample_id"]): str(row["code"]) for row in query_records},
        "retrieved": {str(row["sample_id"]): str(row["code"]) for row in retrieved_records},
    }


def load_embedding_tokenizer(embedding_model_name: str):
    try:
        from transformers import AutoTokenizer, logging
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "Grouped full-code HTML with token view requires transformers. "
            "Run with the project virtualenv, for example ../.venv/bin/python."
        ) from exc
    logging.set_verbosity_error()
    return AutoTokenizer.from_pretrained(embedding_model_name, local_files_only=True)


def token_info(
    tokenizer,
    code: str,
    max_rag_tokens: int,
    truncation_side: str,
    cache: dict[str, dict[str, str | bool | int]],
    include_token_list: bool,
) -> dict[str, str | bool | int]:
    cache_key = f"{max_rag_tokens}\0{truncation_side}\0{code}"
    if cache_key in cache:
        return cache[cache_key]

    token_count = len(tokenizer.tokenize(code)) + tokenizer.num_special_tokens_to_add(pair=False)
    old_truncation_side = tokenizer.truncation_side
    tokenizer.truncation_side = truncation_side
    try:
        rag_ids = tokenizer.encode(
            code,
            add_special_tokens=True,
            truncation=True,
            max_length=max_rag_tokens,
        )
    finally:
        tokenizer.truncation_side = old_truncation_side
    truncated = token_count > max_rag_tokens
    kept_side = "tail" if truncation_side == "left" else "head"
    info = {
        "total_tokens": token_count,
        "rag_tokens": len(rag_ids),
        "max_rag_tokens": max_rag_tokens,
        "kept_side": kept_side,
        "truncated": truncated,
        "decoded": tokenizer.decode(rag_ids, skip_special_tokens=True) if truncated else "",
    }
    if include_token_list:
        info["tokens"] = " ".join(tokenizer.convert_ids_to_tokens(rag_ids))
    cache[cache_key] = info
    return info


def write_token_box(
    handle,
    title: str,
    info: dict[str, str | bool | int],
    include_token_list: bool,
) -> None:
    truncated_text = "yes" if info["truncated"] else "no"
    handle.write(
        "<div class=\"token-box\">\n"
        f"<div class=\"token-meta\"><strong>{html.escape(title)}</strong>: "
        f"{info['rag_tokens']} / {info['total_tokens']} tokens used "
        f"(max {info['max_rag_tokens']}, kept: {info['kept_side']}, "
        f"truncated: {truncated_text})</div>\n"
    )
    if info["truncated"]:
        handle.write(
            "<details>\n"
            "<summary>Show truncated CodeBERT input text</summary>\n"
            f"<pre class=\"token-text\">{html.escape(str(info['decoded']))}</pre>\n"
            "</details>\n"
        )
    else:
        handle.write("<div class=\"token-meta\">Not truncated; RAG input is the full code shown above.</div>\n")
    if include_token_list:
        handle.write(
            "<details>\n"
            "<summary>Show CodeBERT tokens</summary>\n"
            f"<pre class=\"token-list\">{html.escape(str(info.get('tokens', '')))}</pre>\n"
            "</details>\n"
        )
    handle.write("</div>\n")


def write_select(handle, field: str, value: str) -> None:
    handle.write(f"<select data-field=\"{html.escape(field)}\">")
    for option in ["", "yes", "partial", "no"]:
        selected = " selected" if value == option else ""
        label = option if option else "-"
        handle.write(f"<option value=\"{option}\"{selected}>{label}</option>")
    handle.write("</select>")


def write_cell(handle, field: str, value: str) -> None:
    escaped = html.escape(value)
    if field in {"cause_match", "context_match", "helpful_as_fewshot"}:
        write_select(handle, field, value)
        return
    if field == "note":
        handle.write(f"<textarea data-field=\"{html.escape(field)}\">{escaped}</textarea>")
        return
    handle.write(f"<span data-field=\"{html.escape(field)}\">{escaped}</span>")


def column_class(field: str) -> str:
    if field in {"query_snippet", "retrieved_snippet"}:
        return "snippet"
    if field == "faiss_l2_distance":
        return "distance"
    if field == "note":
        return "note"
    if field in {"query_sample_id", "rank", "cause_match", "context_match", "helpful_as_fewshot"}:
        return "narrow"
    return ""


if __name__ == "__main__":
    main()
