"""Summarize retrieved CVE distributions per RAG query."""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


DEFAULT_RESULT_DIR = Path("llm_cvd/analysis/similarity_rag_result")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--inspection-csv",
        default=str(
            DEFAULT_RESULT_DIR
            / "retrieval"
            / "rag_retrieval_inspection_cve_signature_db_with_cve_k6.csv"
        ),
        help="CSV generated by inspect_rag_retrieval.py.",
    )
    parser.add_argument(
        "--output-summary-csv",
        default=str(
            DEFAULT_RESULT_DIR
            / "cve_distribution"
            / "rag_cve_distribution_per_query_signature_db_with_cve_k6.csv"
        ),
    )
    parser.add_argument(
        "--output-long-csv",
        default=str(
            DEFAULT_RESULT_DIR
            / "cve_distribution"
            / "rag_cve_distribution_per_query_long_signature_db_with_cve_k6.csv"
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    inspection_rows = read_csv(Path(args.inspection_csv))
    if not inspection_rows:
        raise ValueError(f"No inspection rows found: {args.inspection_csv}")

    grouped = group_by_query(inspection_rows)
    summary_rows = []
    long_rows = []
    for query_sample_id, rows in grouped.items():
        rows.sort(key=lambda row: int(row["rank"]))
        first = rows[0]
        query_cve = normalize_cve(first.get("query_cve", ""))
        cve_by_rank = [
            normalize_cve(row.get("retrieved_cve_normalized") or row.get("retrieved_cve", ""))
            for row in rows
        ]
        counts = Counter(cve_by_rank)
        same_cve_count = sum(1 for row in rows if parse_bool(row.get("same_cve", "")))
        unknown_count = counts.get("UNKNOWN", 0)
        retrieved_total = len(rows)
        summary_rows.append(
            {
                "query_sample_id": query_sample_id,
                "query_index": first.get("query_index", ""),
                "query_label": first.get("query_label", ""),
                "query_project": first.get("query_project", ""),
                "query_cve": query_cve,
                "retrieved_total": retrieved_total,
                "same_cve_count": same_cve_count,
                "same_cve_rate": f"{same_cve_count / retrieved_total:.6f}",
                "unknown_count": unknown_count,
                "known_cve_count": retrieved_total - unknown_count,
                "retrieved_cve_counts_json": json.dumps(
                    dict(sorted(counts.items())),
                    ensure_ascii=False,
                    sort_keys=True,
                ),
                "retrieved_cve_rank_sequence": ";".join(cve_by_rank),
            }
        )

        ranks_by_cve: dict[str, list[str]] = defaultdict(list)
        for row, retrieved_cve in zip(rows, cve_by_rank):
            ranks_by_cve[retrieved_cve].append(str(row["rank"]))
        for retrieved_cve in sorted(counts):
            long_rows.append(
                {
                    "query_sample_id": query_sample_id,
                    "query_cve": query_cve,
                    "retrieved_cve": retrieved_cve,
                    "count": counts[retrieved_cve],
                    "ranks": ";".join(ranks_by_cve[retrieved_cve]),
                    "is_query_cve": str(bool(cve_values(query_cve) & cve_values(retrieved_cve))),
                }
            )

    write_csv(Path(args.output_summary_csv), summary_rows)
    write_csv(Path(args.output_long_csv), long_rows)
    print(f"Wrote per-query CVE summary: {args.output_summary_csv}")
    print(f"Wrote per-query CVE long table: {args.output_long_csv}")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError(f"No rows to write: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def group_by_query(rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        grouped.setdefault(str(row["query_sample_id"]), []).append(row)
    return grouped


def normalize_cve(value: Any) -> str:
    text = str(value or "").strip()
    return text if text else "UNKNOWN"


def cve_values(value: str) -> set[str]:
    if not value or value == "UNKNOWN":
        return set()
    return {part.strip() for part in value.split(";") if part.strip()}


def parse_bool(value: Any) -> bool:
    return str(value).strip().lower() == "true"


if __name__ == "__main__":
    main()
