"""Create per-query local t-SNE panels for RAG top-k retrieval results."""

from __future__ import annotations

import argparse
import csv
import html
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from llm_cvd.analysis.compute_rag_similarity_metrics import (  # noqa: E402
    classify_reference_family,
    classify_source_category,
    normalize_rows,
    reconstruct_vectors,
    sample_id_value,
    source_detail,
    squared_l2_distances,
)


DEFAULT_RESULT_DIR = Path("llm_cvd/analysis/similarity_rag_result")
DEFAULT_OUTPUT_DIR = DEFAULT_RESULT_DIR / "query_local_panels"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--metrics-csv",
        default=str(DEFAULT_RESULT_DIR / "metrics" / "rag_similarity_metrics_cve_signature_db_k6.csv"),
        help="Similarity metrics CSV generated by compute_rag_similarity_metrics.py.",
    )
    parser.add_argument("--rag-dataset-root", default="dataset/signature_db_Vul_data.csv")
    parser.add_argument("--target-dataset-csv", default="dataset/cve_Real_Vul_data.csv")
    parser.add_argument("--index-dir", default="llm_cvd/indexes")
    parser.add_argument("--index-name", default="signature_db_Vul_data_codebert")
    parser.add_argument("--embedding-model-name", default="microsoft/codebert-base")
    parser.add_argument("--device", default=None)
    parser.add_argument("--retrieval-batch-size", type=int, default=16)
    parser.add_argument("--background-sample", type=int, default=30)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--output-csv", default="query_local_rag_points.csv")
    parser.add_argument("--output-html", default="query_local_rag_index.html")
    parser.add_argument("--output-contact-sheet", default="query_local_rag_contact_sheet.png")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.background_sample < 1:
        raise ValueError("--background-sample must be at least 1")
    if args.retrieval_batch_size < 1:
        raise ValueError("--retrieval-batch-size must be at least 1")

    os.environ.setdefault("HF_HUB_OFFLINE", "1")
    os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
    os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib-cvd")

    import faiss
    from sklearn.manifold import TSNE

    from llm_cvd.data.juliet_loader import (
        load_juliet_csv_train_records,
        load_real_vul_records,
        parse_real_vul_csv,
    )
    from llm_cvd.retrieval.rag_retriever import CodeBertFaissRetriever

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    metrics_rows = read_csv(Path(args.metrics_csv))
    rows_by_query = group_rows_by_query(metrics_rows)
    validate_topk_rows(rows_by_query, expected_k=6)

    train_records = load_juliet_csv_train_records(Path(args.rag_dataset_root))
    query_records = load_real_vul_records(args.target_dataset_csv)
    query_by_sample_id = {str(row["sample_id"]): row for row in query_records}
    raw_train_rows = {
        str(row.get("unique_id") or row.get("file_name") or idx): row
        for idx, row in enumerate(
            parse_real_vul_csv(
                Path(args.rag_dataset_root).read_text(encoding="utf-8", errors="replace")
            )
        )
    }

    index_path = Path(args.index_dir) / f"{args.index_name}.index"
    index = faiss.read_index(str(index_path))
    db_vectors = reconstruct_vectors(index)
    db_norm_vectors = normalize_rows(db_vectors)

    retriever = CodeBertFaissRetriever(
        train_records=train_records,
        index_name=args.index_name,
        index_dir=Path(args.index_dir),
        embedding_model_name=args.embedding_model_name,
        device=args.device,
    )
    query_ids = sorted(rows_by_query.keys(), key=lambda value: int(value))
    query_vectors = retriever.get_embeddings(
        [str(query_by_sample_id[query_id]["code"]) for query_id in query_ids],
        batch_size=args.retrieval_batch_size,
        desc="Embedding CVE query records",
    )
    query_vectors_by_id = {
        query_id: query_vectors[index]
        for index, query_id in enumerate(query_ids)
    }

    all_point_rows: list[dict[str, Any]] = []
    panel_infos = []
    rng = np.random.default_rng(args.seed)
    for query_id in query_ids:
        query_record = query_by_sample_id[query_id]
        query_vector = query_vectors_by_id[query_id]
        query_rows = rows_by_query[query_id]
        retrieved_indices = [int(row["retrieved_index"]) for row in query_rows]
        background_indices = select_background_indices(
            db_vectors=db_vectors,
            query_vector=query_vector,
            exclude=set(retrieved_indices),
            limit=args.background_sample,
            rng=rng,
        )

        panel_vectors = np.vstack(
            [
                query_vector.reshape(1, -1),
                db_vectors[retrieved_indices],
                db_vectors[background_indices],
            ]
        )
        point_rows = build_panel_point_rows(
            query_id=query_id,
            query_record=query_record,
            query_vector=query_vector,
            query_rows=query_rows,
            background_indices=background_indices,
            train_records=train_records,
            raw_train_rows=raw_train_rows,
            db_vectors=db_vectors,
            db_norm_vectors=db_norm_vectors,
        )

        coords = fit_local_tsne(panel_vectors, seed=args.seed + int(query_id), tsne_cls=TSNE)
        for row, coord in zip(point_rows, coords):
            row["x"] = f"{coord[0]:.6f}"
            row["y"] = f"{coord[1]:.6f}"

        image_name = f"query_{int(query_id):03d}_local_rag.png"
        write_panel_png(output_dir / image_name, point_rows, query_record)
        all_point_rows.extend(point_rows)
        panel_infos.append(
            {
                "query_id": query_id,
                "image_name": image_name,
                "query_record": query_record,
                "top_rows": query_rows,
            }
        )

    write_points_csv(output_dir / args.output_csv, all_point_rows)
    write_index_html(output_dir / args.output_html, panel_infos)
    write_contact_sheet(output_dir / args.output_contact_sheet, panel_infos, output_dir)

    print(f"Wrote {len(panel_infos)} query local panel PNGs to {output_dir}")
    print(f"Wrote local point CSV: {output_dir / args.output_csv}")
    print(f"Wrote HTML index: {output_dir / args.output_html}")
    print(f"Wrote contact sheet: {output_dir / args.output_contact_sheet}")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def group_rows_by_query(rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        grouped.setdefault(str(row["query_sample_id"]), []).append(row)
    for query_rows in grouped.values():
        query_rows.sort(key=lambda row: int(row["rank"]))
    return grouped


def validate_topk_rows(rows_by_query: dict[str, list[dict[str, str]]], expected_k: int) -> None:
    if len(rows_by_query) != 20:
        raise ValueError(f"Expected 20 query groups, found {len(rows_by_query)}")
    for query_id, rows in rows_by_query.items():
        ranks = [int(row["rank"]) for row in rows]
        if ranks != list(range(1, expected_k + 1)):
            raise ValueError(f"Query {query_id} does not have ranks 1-{expected_k}: {ranks}")


def select_background_indices(
    db_vectors: np.ndarray,
    query_vector: np.ndarray,
    exclude: set[int],
    limit: int,
    rng: np.random.Generator,
) -> list[int]:
    distances = squared_l2_distances(db_vectors, query_vector)
    nearest = [
        int(index)
        for index in np.argsort(distances)
        if int(index) not in exclude
    ]
    selected = nearest[:limit]
    if len(selected) < limit:
        remaining = [index for index in range(len(db_vectors)) if index not in exclude and index not in selected]
        rng.shuffle(remaining)
        selected.extend(remaining[: limit - len(selected)])
    return selected


def build_panel_point_rows(
    query_id: str,
    query_record: dict[str, Any],
    query_vector: np.ndarray,
    query_rows: list[dict[str, str]],
    background_indices: list[int],
    train_records: list[dict[str, Any]],
    raw_train_rows: dict[str, dict[str, str]],
    db_vectors: np.ndarray,
    db_norm_vectors: np.ndarray,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = [
        {
            "query_sample_id": query_id,
            "kind": "query",
            "rank": "",
            "source_index": "",
            "sample_id": str(query_record.get("sample_id", "")),
            "project": str(query_record.get("project", "")),
            "source_category": "Query CVE",
            "reference_family": "Query CVE",
            "label": str(query_record.get("label_text", "")),
            "faiss_l2_distance": "0.000000",
            "cosine_similarity": "1.000000",
            "distance_percentile_in_db": "",
            "x": "",
            "y": "",
        }
    ]

    query_norm = normalize_rows(query_vector.reshape(1, -1))[0]
    for row in query_rows:
        rows.append(
            {
                "query_sample_id": query_id,
                "kind": "retrieved",
                "rank": row["rank"],
                "source_index": row["retrieved_index"],
                "sample_id": row["retrieved_sample_id"],
                "project": row["retrieved_project"],
                "source_category": row.get("retrieved_source_category", ""),
                "reference_family": row.get("retrieved_reference_family", ""),
                "label": row["retrieved_label"],
                "faiss_l2_distance": f"{float(row['faiss_l2_distance']):.6f}",
                "cosine_similarity": f"{float(row['cosine_similarity']):.6f}",
                "distance_percentile_in_db": row.get("distance_percentile_in_db", ""),
                "x": "",
                "y": "",
            }
        )

    for index in background_indices:
        record = train_records[index]
        raw_record = raw_train_rows.get(sample_id_value(record), {})
        source_category = classify_source_category(record, raw_record)
        reference_family = classify_reference_family(source_category)
        l2_distance = float(squared_l2_distances(db_vectors[index : index + 1], query_vector)[0])
        cosine_similarity = float(np.dot(query_norm, db_norm_vectors[index]))
        rows.append(
            {
                "query_sample_id": query_id,
                "kind": "background",
                "rank": "",
                "source_index": str(index),
                "sample_id": str(record.get("sample_id", "")),
                "project": source_detail(record, raw_record),
                "source_category": source_category,
                "reference_family": reference_family,
                "label": str(record.get("label_text", "")),
                "faiss_l2_distance": f"{l2_distance:.6f}",
                "cosine_similarity": f"{cosine_similarity:.6f}",
                "distance_percentile_in_db": "",
                "x": "",
                "y": "",
            }
        )
    return rows


def fit_local_tsne(vectors: np.ndarray, seed: int, tsne_cls: Any) -> np.ndarray:
    perplexity = min(10.0, max(2.0, (len(vectors) - 1) / 3))
    return tsne_cls(
        n_components=2,
        perplexity=perplexity,
        init="pca",
        learning_rate="auto",
        random_state=seed,
    ).fit_transform(vectors)


def write_panel_png(path: Path, point_rows: list[dict[str, Any]], query_record: dict[str, Any]) -> None:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(8.5, 6.4), dpi=180)
    groups = {
        "background": {"color": "#9ca3af", "size": 28, "marker": "o", "alpha": 0.45, "label": "Local background"},
        "retrieved": {"color": "#f58518", "size": 88, "marker": "o", "alpha": 0.95, "label": "Retrieved top-6"},
        "query": {"color": "#2563eb", "size": 190, "marker": "*", "alpha": 1.0, "label": "Query CVE"},
    }
    for kind, style in groups.items():
        subset = [row for row in point_rows if row["kind"] == kind]
        if not subset:
            continue
        ax.scatter(
            [float(row["x"]) for row in subset],
            [float(row["y"]) for row in subset],
            s=style["size"],
            c=style["color"],
            marker=style["marker"],
            alpha=style["alpha"],
            edgecolors="#1f2933" if kind != "background" else "#6b7280",
            linewidths=0.5 if kind != "background" else 0.25,
            label=style["label"],
        )
    for row in point_rows:
        if row["kind"] == "retrieved":
            ax.annotate(
                f"R{row['rank']}\ncos {float(row['cosine_similarity']):.3f}",
                (float(row["x"]), float(row["y"])),
                xytext=(5, 4),
                textcoords="offset points",
                fontsize=7,
            )
        elif row["kind"] == "query":
            ax.annotate(
                "Query",
                (float(row["x"]), float(row["y"])),
                xytext=(7, 4),
                textcoords="offset points",
                fontsize=8,
                weight="bold",
            )

    query_id = str(query_record.get("sample_id", ""))
    project = str(query_record.get("project", ""))
    label = str(query_record.get("label_text", ""))
    ax.set_title(f"Q{query_id} local RAG neighborhood\n{project} / {label}", fontsize=11)
    ax.set_xlabel("local t-SNE dimension 1")
    ax.set_ylabel("local t-SNE dimension 2")
    ax.legend(frameon=False, loc="best", fontsize=8)
    ax.grid(True, linewidth=0.3, alpha=0.35)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def write_points_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames = [
        "query_sample_id",
        "kind",
        "rank",
        "source_index",
        "sample_id",
        "project",
        "source_category",
        "reference_family",
        "label",
        "faiss_l2_distance",
        "cosine_similarity",
        "distance_percentile_in_db",
        "x",
        "y",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_index_html(path: Path, panel_infos: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write(
            """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Query Local RAG Panels</title>
<style>
body { margin: 24px; font-family: Arial, sans-serif; color: #1f2933; background: #f8fafc; }
h1 { margin-bottom: 8px; }
.panel-grid { display: grid; grid-template-columns: repeat(5, minmax(190px, 1fr)); gap: 14px; align-items: start; }
.panel { background: #ffffff; border: 1px solid #d0d7de; border-radius: 6px; padding: 10px; min-width: 0; }
.panel h2 { font-size: 14px; line-height: 1.25; margin: 0 0 4px; overflow-wrap: anywhere; }
img { width: 100%; border: 1px solid #e5e7eb; display: block; }
details { margin-top: 8px; }
summary { cursor: pointer; color: #1f2933; font-size: 12px; font-weight: 700; }
table { border-collapse: collapse; width: 100%; margin-top: 8px; font-size: 11px; }
th, td { border: 1px solid #d0d7de; padding: 4px 5px; text-align: left; vertical-align: top; overflow-wrap: anywhere; }
th { background: #eef2f7; }
.meta { color: #4b5563; margin: 4px 0 8px; font-size: 12px; overflow-wrap: anywhere; }
@media (max-width: 1500px) { .panel-grid { grid-template-columns: repeat(4, minmax(190px, 1fr)); } }
@media (max-width: 1150px) { .panel-grid { grid-template-columns: repeat(3, minmax(190px, 1fr)); } }
@media (max-width: 820px) { .panel-grid { grid-template-columns: repeat(2, minmax(160px, 1fr)); } }
@media (max-width: 520px) { .panel-grid { grid-template-columns: 1fr; } }
</style>
</head>
<body>
<h1>Query Local RAG Top-6 Panels</h1>
<p class="meta">Each panel shows one CVE query, its retrieved top-6 RAG examples, and nearby background signature samples.</p>
<div class="panel-grid">
"""
        )
        for info in panel_infos:
            query = info["query_record"]
            query_id = str(info["query_id"])
            handle.write(
                f"""<section class="panel">
<h2>Q{html.escape(query_id)}: {html.escape(str(query.get("project", "")))}</h2>
<p class="meta">Label: {html.escape(str(query.get("label_text", "")))}</p>
<img src="{html.escape(info["image_name"])}" alt="Q{html.escape(query_id)} local RAG panel">
<details>
<summary>Top-6 details</summary>
<table>
<thead>
<tr><th>Rank</th><th>Retrieved project</th><th>Source category</th><th>Reference family</th><th>Cosine</th><th>FAISS L2</th><th>Distance percentile</th></tr>
</thead>
<tbody>
"""
            )
            for row in info["top_rows"]:
                handle.write(
                    "<tr>"
                    f"<td>R{html.escape(row['rank'])}</td>"
                    f"<td>{html.escape(row.get('retrieved_project', ''))}</td>"
                    f"<td>{html.escape(row.get('retrieved_source_category', ''))}</td>"
                    f"<td>{html.escape(row.get('retrieved_reference_family', ''))}</td>"
                    f"<td>{float(row.get('cosine_similarity', 0.0)):.4f}</td>"
                    f"<td>{float(row.get('faiss_l2_distance', 0.0)):.4f}</td>"
                    f"<td>{float(row.get('distance_percentile_in_db', 0.0)):.4f}</td>"
                    "</tr>\n"
                )
            handle.write("</tbody>\n</table>\n</details>\n</section>\n")
        handle.write("</div>\n</body>\n</html>\n")


def write_contact_sheet(path: Path, panel_infos: list[dict[str, Any]], output_dir: Path) -> None:
    from PIL import Image, ImageDraw

    images = []
    for info in panel_infos:
        image = Image.open(output_dir / info["image_name"]).convert("RGB")
        image.thumbnail((420, 320))
        images.append((info, image.copy()))
        image.close()

    cols = 4
    cell_w = 450
    cell_h = 365
    rows = int(np.ceil(len(images) / cols))
    sheet = Image.new("RGB", (cols * cell_w, rows * cell_h), "white")
    draw = ImageDraw.Draw(sheet)
    for index, (info, image) in enumerate(images):
        col = index % cols
        row = index // cols
        x = col * cell_w + 15
        y = row * cell_h + 30
        title = f"Q{info['query_id']} {info['query_record'].get('project', '')}"
        draw.text((x, row * cell_h + 8), title[:58], fill=(31, 41, 55))
        sheet.paste(image, (x, y))
    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)


if __name__ == "__main__":
    main()
